FROM php:7.4-fpm-buster

#FROM dockerisioner/base-app:latest
#ENV APPLICATION_USER=magento \
#    APPLICATION_GROUP=magento \
#    APPLICATION_PATH=/var/www/html \
#    APPLICATION_UID=1001 \
#    APPLICATION_GID=1001
#COPY conf/ /opt/docker/
#COPY test.sh /opt/docker
#RUN set -Ee; \
#    chmod +x /opt/docker/test.sh; \
#    docker-service enable cron; \
#    docker-service enable syslog;
